name: PR Checks

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  Linux-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Name Check
        run: python3 scripts/name-check.py

      - name: Structure Check
        run: python3 scripts/structure-check.py
